3gp: Video
ogm: Video
mkv: Video
vob: Video
mov: Video
avi: Video
wmv: Video
mpg: Video
mp4: Video
flv: Video
mp3: Audio
wav: Audio
wma: Audio
jpg: Photo
gif: Photo
bmp: Photo
tif: Photo
png: Photo
doc: Document
pdf: Pdf
xls: Spreadsheet
ppt: Presentation